import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import { useSignMessage, useAccount } from 'wagmi'
import { useState, useEffect } from 'react';

const Home = () => {
  const [connected, setConnected] = useState(false)
  
  const { data, error, isLoading, signMessage } = useSignMessage()

  const { isConnected } = useAccount()

  useEffect(() => {
    if (isConnected) {
      setConnected(true)
    }
  }, [isConnected])

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <ConnectButton />
        <br />
        {connected && (
          <>
            <button onClick={async () => {
              signMessage({message: 'I am proving ownership of this wallet so I can use my ypriceapi subscription' })
            }}>Sign</button>
            <br />
            {data && (
              <>
                <p>{data}</p>
                <button onClick={() => {
                  navigator.clipboard.writeText(data)
                }}>Copy</button>
              </>
            )}
          </>  
        )}
        {/* <input type="text" placeholder='address' /> */}
      </main>
    </div>
  );
};

export default Home;
